apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pact-broker.fullname" . }}
  labels:
    app: {{ template "pact-broker.name" . }}
    chart: {{ template "pact-broker.chart" . }}
    release: {{ .Release.Name | quote }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pact-broker.name" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ template "pact-broker.name" . }}
        chart: {{ template "pact-broker.chart" . }}
        release: {{ .Release.Name | quote }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
      {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: 
      {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: 
      {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: 
      {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ default (include "postgresql.fullname" . ) .Values.serviceAccount.name }}
      {{- end }}
      containers:
      - name: {{ template "pact-broker.name" . }}
        image: {{ template "pact-broker.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: PACT_BROKER_DATABASE_HOST
          value: {{ template "pact-broker.postgresql.fullname" . }}
        - name: PACT_BROKER_DATABASE_NAME
          value: {{ .Values.postgresql.postgresqlDatabase }}
        - name: PACT_BROKER_DATABASE_USERNAME
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: PACT_BROKER_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $.Release.Name }}-postgresql
              key: "postgresql-password"
        - name: PACT_BROKER_PORT 
          value: "9292"
        - name: PACT_BROKER_PUBLIC_HEARTBEAT
          value: "true"
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ ternary "https" "http" .Values.healthcheckHttps }}
            {{- if .Values.healthcheckHttps }}
            scheme: HTTPS
            {{- end }}
            {{- if .Values.livenessProbe.headers }}
            httpHeaders: 
            {{- toYaml .Values.livenessProbe.headers | nindent 16 }}
            {{- end }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ ternary "https" "http" .Values.healthcheckHttps }}
            {{- if .Values.healthcheckHttps }}
            scheme: HTTPS
            {{- end }}
            {{- if .Values.readinessProbe.headers }}
            httpHeaders: 
            {{- toYaml .Values.readinessProbe.headers | nindent 16 }}
            {{- end }}
        {{- end }}
        resources:
        {{- toYaml .Values.resources | nindent 12 }}