apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{- else }}
  name: {{ template "pact-broker.fullname" . }}
  {{- end }}
  labels:
    app: {{ template "pact-broker.name" . }}
    chart: {{ template "pact-broker.chart" . }}
    release: {{ .Release.Name | quote }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "pact-broker.name" . }}
    release: {{ .Release.Name | quote }}
