image:
  registry: pactfoundation
  repository: pact-broker
  tag: 2.52.2-1

replicaCount: 1

service:
  name: pact-broker
  type: ClusterIP
  externalPort: 80
  internalPort: 9292

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlDatabase: pact_broker

securityContext:
  enabled: false

serviceAccount:
  enabled: false

livenessProbe:
  enabled: false
  path: /diagnostic/status/heartbeat
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: false
  path: /diagnostic/status/heartbeat
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

healthcheckHttps: false

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi